// <auto-generated />
using System;
using AdminServiceDotNET.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminServiceDotNET.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260206070014_AddIsActiveToBatch")]
    partial class AddIsActiveToBatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdminServiceDotNET.Models.Announcement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("announcement_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("created_by_email");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_by_role");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("target_role");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_announcement_created_at");

                    b.HasIndex(new[] { "TargetRole" }, "idx_announcement_target_role");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("AdminServiceDotNET.Models.AuditLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("details");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_role");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("service_name");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("user_email");

                    b.HasKey("Id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("AdminServiceDotNET.Models.Batch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("batch_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("BatchName")
                        .IsUnique();

                    b.HasIndex(new[] { "BatchName" }, "idx_batch_batch_name");

                    b.HasIndex(new[] { "EndDate" }, "idx_batch_end_date");

                    b.HasIndex(new[] { "StartDate" }, "idx_batch_start_date");

                    b.ToTable("batches");
                });

            modelBuilder.Entity("AdminServiceDotNET.Models.SystemSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("settings_id");

                    b.Property<bool>("ExamAutoSubmit")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("exam_auto_submit");

                    b.Property<bool>("FullscreenEnforcement")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("fullscreen_enforcement");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("maintenance_mode");

                    b.Property<bool>("TabSwitchDetection")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tab_switch_detection");

                    b.HasKey("Id");

                    b.ToTable("system_settings");
                });
#pragma warning restore 612, 618
        }
    }
}
